{
 "title": "OpenEVSE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Charge Efficiency vs OpenEVSE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "openevse = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"wattsec\")\n  |> map(fn: (r) => ({r with _value: r._value / 3600.0 / 1000.0 }))\n  |> truncateTimeColumn(unit: 1m)\n  |> drop(columns: [\"url\", \"_measurement\"])\n|>yield(name: \"openevse\")\nrivian = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rivian\" and r._field == \"Charge Session\")\n  |> truncateTimeColumn(unit: 1m)\n  |> drop(columns: [\"_measurement\", \"table\"])\n  |> yield(name: \"rivian\")\nunion(tables: [rivian, openevse])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"Charge Session\": \"charge_session\"})\n  |> map(fn: (r) => ({ r with _value: r.charge_session / r.wattsec}))\n  |> drop(columns: [\"charge_session\", \"wattsec\", \"_stop\", \"_start\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)  \n  |> rename(columns: {\"_value\": \"Charge Efficiency vs OpenEVSE\"})\n  \n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"amp\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 * 0.24}))\n  |> yield(name: \"kW\")"
    },
    {
     "query": "pilot = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"pilot\")\nvoltage = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"voltage\")\nunion(tables: [voltage, pilot])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.pilot * r.voltage / 1000.0 }))  \n  |> drop(columns: [\"voltage\", \"pilot\", \"url\"])  "
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"temp1\")\n  |> map(fn: (r) => ({r with _value: r._value / 10.0 }))\n  |> yield(name: \"c\")"
    }
   ]
  },
  {
   "title": "Elapsed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"elapsed\")\n  |> map(fn: (r) => ({r with _value: r._value / 3600.0 }))\n  |> drop(columns: [\"url\"])"
    }
   ]
  },
  {
   "title": "Session",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"wattsec\")\n  |> map(fn: (r) => ({r with _value: r._value / 3600.0 / 1000.0 }))\n  |> drop(columns: [\"url\"])"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"watthour\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 }))\n  |> yield(name: \"kWh\")"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"state\")\n  |> drop(columns: [\"_start\", \"_stop\", \"url\"])\n  |> toString()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"amp\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\n  |> drop(columns: [\"url\"])"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"pilot\")\n  |> drop(columns: [\"url\"])"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"temp1\")\n  |> map(fn: (r) => ({r with _value: r._value / 10.0}))\n  |> drop(columns: [\"url\"])"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\" and r._field == \"wattsec\")\n  |> map(fn: (r) => ({r with _value: r._value / 3600.0 / 1000.0 }))\n  |> drop(columns: [\"url\"])"
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"gfcicount\" or\n      r._field == \"nogndcount\" or\n      r._field == \"srssi\" or\n      r._field == \"stuckcount\")\n  |> drop(columns: [\"url\"])"
    },
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"comm_sent\")\n  |> aggregate.rate(every: 5m, unit: 5m)\n  |> drop(columns: ([\"_start\", \"_stop\"]))\n  |> rename(columns: {\"_value\": \"Rate comm_sent\"})"
    },
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"openevse\")\n  |> filter(fn: (r) => r._field == \"comm_success\")\n  |> aggregate.rate(every: 5m, unit: 5m)\n  |> drop(columns: ([\"_start\", \"_stop\"]))\n  |> rename(columns: {\"_value\": \"Rate comm_success\"})"
    }
   ]
  }
 ]
}